---
- name: tao interface loopback
  hosts: all
  gather_facts: no

  tasks:
    - name: Create loopback
      ios_l3_interface:
        name: loopback {{item.number}}
        ipv4: 10.0.{{item.number}}.1/24

        state: present
      with_items:
        - { number: 0 }
        - { number: 1 }
        - { number: 2 }

    - name: Show interface brief
      ios_command:
        commands:
          - show ip interface brief

      register: show_interface

    - debug: var=show_interface.stdout_lines
